# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 'CS 5805 Project'
#author: Leo, Pranesh, Mohammad, and Roshan
#logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/1stl0ve/cs5805-project

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  home_page_in_navbar: false
  search: false  # Disable the search bar
  single_page: false # Ensures a single-page layout
  extra_css: ["_static/custom.css"]
  search: false  # Disable the search bar
  use_sidenotes: true  # Enable right-side navigation for content
  extra_navbar: ""  # Removes any extra navbar elements
  extra_footer: ""  # Removes any extra footer content

  # Optional: Hide left sidebar completely
  sidebars: {
    left: [],
    right: ["sidenav"]
  }
